management:
  security:
    enabled: false

server:
  port: ${port:8080}

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    
    
  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka}
